const colors = require('tailwindcss/colors');

module.exports = {
  darkMode: 'class',
  mode: 'jit',
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/line-clamp'),
  ],
  content: [
    './src/shared/**/*.{js,jsx,ts,tsx}',
    './src/compositions/**/*.{js,jsx,ts,tsx}',
    './src/composables/**/*.{js,jsx,ts,tsx}',
    './src/components/**/*.{js,jsx,ts,tsx}',
    './src/templates/**/*.{js,jsx,ts,tsx}',
  ],
  safelist: [
    'my-8',
    'px-[40px]',
    'rounded-[40px]',
    'text-p2-underlined',
    'bg-background',
    'grid-cols-1',
    'grid-cols-2',
    'grid-cols-3',
    'grid-cols-4',
    'grid-cols-5',
    'grid-cols-6',
    'grid-cols-7',
    'grid-cols-8',
    'grid-cols-9',
    'grid-cols-10',
    'grid-cols-11',
    'grid-cols-12',
    'grid-rows-1',
    'grid-rows-2',
    'grid-rows-3',
    'grid-rows-4',
    'grid-rows-5',
    'grid-rows-6',
    'grid-rows-7',
    'grid-rows-8',
    'grid-rows-9',
    'grid-rows-10',
    'grid-rows-11',
    'grid-rows-12',
    'col-span-1',
    'col-span-2',
    'col-span-3',
    'col-span-4',
    'col-span-5',
    'col-span-6',
    'col-span-7',
    'col-span-8',
    'col-span-9',
    'col-span-10',
    'col-span-11',
    'col-span-12',
    'h-v56',
    'mt-[20px]',
    'text-display-bold',
    'text-display-semi-bold',
    'text-display-extra-bold',
    'text-h1-bold',
    'text-h1-semi-bold',
    'text-h1-extra-bold',
    'text-h2-bold',
    'text-h2-semi-bold',
    'text-h2-extra-bold',
    'text-h2-bold',
    'text-h2-semi-bold',
    'text-h2-extra-bold',
    'text-h3-bold',
    'text-h3-semi-bold',
    'text-h3-extra-bold',
    'text-h3-bold',
    'text-h3-semi-bold',
    'text-h3-extra-bold',
    'text-h4-bold',
    'text-h4-semi-bold',
    'text-h4-extra-bold',
    'text-h4-bold',
    'text-h4-semi-bold',
    'text-h4-extra-bold',
    'text-subheading-bold',
    'text-subheading-semi-bold',
    'text-subheading-extra-bold',
    'text-subheading-medium',
    'text-subheading-bold',
    'text-subheading-underlined',
    'text-subheading-light',
    'text-p1-medium',
    'text-p1-bold',
    'text-p1-underlined',
    'text-p1-light',
    'text-p2-medium',
    'text-p2-bold',
    'text-p2-underlined',
    'text-p2-light',
    'text-p3-medium',
    'text-p3-bold',
    'text-p3-underlined',
    'text-p3-light',
    'text-caption-medium',
    'text-caption-bold',
    'text-caption-underlined',
    'text-caption-light',
    'text-caption-bold-underlined',
    'text-footer-medium',
    'text-footer-bold',
    'text-footer-underlined',
    'text-footer-light',
    'text-footer-bold-underlined'
  ],
  theme: {
    colors: {
      black: colors.black,
      white: colors.white,
      gray: colors.slate,
      green: colors.green,
      blue: colors.sky,
      indigo: colors.indigo,
      red: colors.rose,
      yellow: colors.amber
    },
    extend: {
      flex: {
        'card': '0 0'
      },
      dropShadow: {
        'short': '0 1px 1px rgba(0, 0, 0, 0.75)',
      },
      animation: {
        marquee: 'marquee 60s linear infinite',
        'marquee-mirror': 'marquee-mirror 60s linear infinite',
        showHide: 'showHide 2s ease infinite',
        'endlessGrid': 'endlessGrid 15s infinite linear',
        'endless': 'endless 10s infinite linear',
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-100%)' },
        },
        'marquee-mirror': {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0%)' },
        },
        showHide: {
          '0%': { opacity: '0' },
          '5%': { opacity: '1' },
          '95%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        endlessGrid: {
          '0%': { 'background-position': '0px -200px,0px 0px' },
          '100%': { 'background-position': '0px 0px, 0px 0px' },
        },
        endless: {
          '0%': { 'transform': 'rotateX(45deg) translateY(-50%)' },
          '100%': { 'transform': 'rotateX(45deg) translateY(0)' },
        },
      },
      borderWidth: {
        '05': '0.5px'
      },
      fontSize: {
        'button-tiny': ['11.7px', '11.7px'],
        'button-small': ['14px', '14px'],
        'button-medium': ['16.8px', '16.8px'],
        'button-large': ['20.2px', '20.2px']
      },
      height: {
        v8: '8vh',
        v16: '16vh',
        v24: '24vh',
        v32: '32vh',
        v40: '40vh',
        v48: '48vh',
        v56: '56vh',
        v68: '68vh',
        v76: '76vh',
        v84: '84vh',
        v92: '92vh',
        safe: 'calc(100vh - env(safe-area-inset-bottom))'
      },
      colors: {
        'primary-100': 'var(--color-primary-100)',
        'primary-200': 'var(--color-primary-200)',
        'primary-300': 'var(--color-primary-300)',
        'primary-400': 'var(--color-primary-400)',
        'primary-500': 'var(--color-primary-500)',
        'primary-600': 'var(--color-primary-600)',
        'primary-700': 'var(--color-primary-700)',
        'primary-800': 'var(--color-primary-800)',
        'primary-900': 'var(--color-primary-900)',
        'primary-1000': 'var(--color-primary-1000)',
        'primary-1100': 'var(--color-primary-1100)',
        'primary-1200': 'var(--color-primary-1200)',
        'primary-1300': 'var(--color-primary-1300)',
        'secondary-100': 'var(--color-secondary-100)',
        'secondary-200': 'var(--color-secondary-200)',
        'secondary-300': 'var(--color-secondary-300)',
        'secondary-400': 'var(--color-secondary-400)',
        'secondary-500': 'var(--color-secondary-500)',
        'secondary-600': 'var(--color-secondary-600)',
        'secondary-700': 'var(--color-secondary-700)',
        'secondary-800': 'var(--color-secondary-800)',
        'secondary-900': 'var(--color-secondary-900)',
        'secondary-1000': 'var(--color-secondary-1000)',
        'secondary-1100': 'var(--color-secondary-1100)',
        'secondary-1200': 'var(--color-secondary-1200)',
        'secondary-1300': 'var(--color-secondary-1300)',
        'tertiary-100': 'var(--color-tertiary-100)',
        'tertiary-200': 'var(--color-tertiary-200)',
        'tertiary-300': 'var(--color-tertiary-300)',
        'tertiary-400': 'var(--color-tertiary-400)',
        'tertiary-500': 'var(--color-tertiary-500)',
        'tertiary-600': 'var(--color-tertiary-600)',
        'tertiary-700': 'var(--color-tertiary-700)',
        'tertiary-800': 'var(--color-tertiary-800)',
        'tertiary-900': 'var(--color-tertiary-900)',
        'tertiary-1000': 'var(--color-tertiary-1000)',
        'tertiary-1100': 'var(--color-tertiary-1100)',
        'tertiary-1200': 'var(--color-tertiary-1200)',
        'tertiary-1300': 'var(--color-tertiary-1300)',
        'neutral-100': 'var(--color-neutral-100)',
        'neutral-200': 'var(--color-neutral-200)',
        'neutral-300': 'var(--color-neutral-300)',
        'neutral-400': 'var(--color-neutral-400)',
        'neutral-500': 'var(--color-neutral-500)',
        'neutral-600': 'var(--color-neutral-600)',
        'neutral-700': 'var(--color-neutral-700)',
        'neutral-800': 'var(--color-neutral-800)',
        'neutral-900': 'var(--color-neutral-900)',
        'neutral-1000': 'var(--color-neutral-1000)',
        'neutral-1100': 'var(--color-neutral-1100)',
        'neutral-1200': 'var(--color-neutral-1200)',
        'neutral-1300': 'var(--color-neutral-1300)',
        white: 'var(--color-white)',
        black: 'var(--color-black)',
        silver: 'var(--color-silver)',
        background: 'var(--color-background)'
      }
    }
  },
  settings: {
    'tailwindCSS.includeLanguages': {
      plaintext: 'javascript'
    },
    'tailwindCSS.emmetCompletions': true
  }
};
